services:
  # A web service
  - type: web
    name: xgboost-model-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free # Adjust as needed (free/starter/standard/etc.)
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    
    # Optional: If you need persistent disk storage for model files
    disk:
      name: model-storage
      mountPath: /app/models
      sizeGB: 1